### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by zigzag-007** [rmdhnreza/rmdhnreza.my.id#2]
After activating Eset 16 with this method, after automatic update to Eset 17, the license gets reset and can't be activated again with this method. 

This method only works for Eset 15/16 with no updates. 

Is there any fix for this issue with Eset 17?

**Comment by rmdhnreza** [comment]
I've been tested on the latest ESET (v17.1.9.0) and still working.

<details>
<summary>ESET v17.1.9.0</summary>

![1](https://github.com/rmdhnreza/rmdhnreza.my.id/assets/23427492/2725af26-d3e3-4089-aeba-6d7cbd235896)

![2](https://github.com/rmdhnreza/rmdhnreza.my.id/assets/23427492/11e5fe3c-fb7a-446d-a89b-5b8aefd12b0d)

![3](https://github.com/rmdhnreza/rmdhnreza.my.id/assets/23427492/b9f1a3eb-ee3f-450d-83ae-f452b5e49f9f)

![4](https://github.com/rmdhnreza/rmdhnreza.my.id/assets/23427492/e8456457-47e4-474b-b753-630caae5bb93)
</details>

Don't use GitHub issue for this, just comment on blog post!
